### ISSUE TITLE
Rythmus pattern (drums, basslines, piano)

### ISSUE THREAD

**Issue by DavidBlaa** [DavidBlaa/kukuwi#7]
> Als Nutzer möchte ich im Spiel mein Rhythmus-Gefühl testen in dem 3 Pattern angezeigt werden und ein Pattern abgespielt wird. Durch die Selektierung einer der Pattern wird ein Ergebnisse angezeigt, ob dass Pattern passt oder nicht. 

![image](https://github.com/user-attachments/assets/cbce2f9d-bc78-4ab6-b5c0-7ce1e1e1fbf7)

## Akzeptanzkriterien
- [ ] 3 Pattern von einer Variante (e.g. Drums) werden angezeigt und eins davon kann ausgewählt werden. 
- [ ] Es gibt 3 Versionen vom Pattern-Level ( Drums, Basslines, Piano)
- [ ] Es gibt 3 Schwierigkeitsgrade (Anzahl der Zeilen 2, 4, 6)

## Task decomposition

- [x] #39
- [x] Drum-Samples erstellen
- [ ] #40
- [ ] #41
